export const tableColumnsConfig = [
    {
        isShow: true,
        label: "派车记录编号",
        prop: "appointCarRecordNo",
        sortNum: 1,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "派车时间",
        prop: "createTime",
        sortNum: 2,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "调度单号",
        prop: "dispatchOrderNo",
        sortNum:3,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "司机",
        prop: "driverName",
        sortNum: 4,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "车辆",
        prop: "vehicleNumber",
        sortNum: 5,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "出车时间",
        prop: "outCarTime",
        sortNum: 6,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "出发地",
        prop: "loadAddress",
        sortNum: 7,
        width:280,
        tooltip: true,
    },
    {
        isShow: true,
        label: "目的地",
        prop: "unloadAddress",
        sortNum: 8,
        width:280,
        tooltip: true,
    },
    {
        isShow: true,
        label: "项目",
        prop: "projectName",
        sortNum: 9,
        width:120,
        tooltip: true,
    },
    // {
    //     isShow: true,
    //     label: "货物大类",
    //     prop: "goodsBigTypeName",
    //     sortNum: 10,
    //     tooltip: true,
    // },
    {
        isShow: true,
        label: "货物类型",
        prop: "goodsSmallTypeName",
        sortNum: 11,
        width:180,
        tooltip: true,
    },
    {
        isShow: true,
        label: "操作",
        prop: "edit",
        sortNum: 12,
        tooltip: true,
        width:'200px',
        fixed:'right'
    },
   

]