export const tableColumnsConfig = [
    {
        isShow: true,
        label: "车辆",
        prop: "plate_number",
        sortNum: 1,
        tooltip: true,
    },
    {
        isShow: true,
        label: "司机",
        prop: "driver_name",
        sortNum: 2,
        tooltip: true,
    },
    {
        isShow: true,
        label: "车辆状态",
        prop: "vehicle_status",
        sortNum: 3,
        tooltip: true,
    },
    {
        isShow: true,
        label: "行驶状态",
        prop: "driverStatus",
        sortNum: 4,
        tooltip: true,
    },
    {
        isShow: true,
        label: "当前位置",
        prop: "realStatus",
        sortNum: 5,
        tooltip: true,
    },
    {
        isShow: true,
        label: "上报时间",
        prop: "enabled",
        sortNum: 6,
        tooltip: true,
    },
    {
        isShow: true,
        label: "设备类型",
        prop: "createTime",
        sortNum: 7,
        tooltip: true,
    },
    {
        isShow: true,
        label: "最近告警",
        prop: "createTime",
        sortNum: 7,
        tooltip: true,
    },
    {
        isShow: true,
        label: "最近告警时间",
        prop: "createTime",
        sortNum: 7,
        tooltip: true,
    },
    {
        isShow: true,
        label: "最近告警位置",
        prop: "createTime",
        sortNum: 7,
        tooltip: true,
    },
    {
        isShow: true,
        label: "操作",
        prop: "edit",
        sortNum: 8,
        tooltip: true,
        width: 200
    },
]